### ISSUE TITLE
Feature request: nicer syntax for object validation

### ISSUE THREAD

**Issue by steph643** [zhaoyao91/meteor-validate#2]
I didn't try the package yet, but it seems an important feature is missing. How do I do this?:

``` javascript
    check(argsAsAnObject, {
      _id      : String,
      projectId: String,
      role     : Match.Optional(String),
      profile  : Match.Optional({
        username: Match.Optional(String),
        picture : Match.Optional(String),
        about   : Match.Optional(String)
      })
    });
```

**Comment by zhaoyao91** [comment]
It can check [sub fields](https://github.com/zhaoyao91/meteor-validate#sub-fields).  
In your case, the code would be like:

```
var arg = {
    id: '1',
    projectId: '2',
    role: 'admin',

    profile: {
        user: 'bob',
        picture: 'some pic',
        about: 'I am bob'
    }
};

var vObject = validate(arg).isObject(); // check argsAsAnObject
vObject.validate('id').isString(); // arg.id
vObject.validate('projectId').isString(); // arg.projectId
vObject.validate('role').optional().isString();
var vProfile = vObject.validate('profile').optional().isObject(); // arg.project
vProfile.validate('user').optional().isString(); // arg.profile.user
vProfile.validate('picture').optional().isString(); // arg.profile.picture
vProfile.validate('about').optional().isString(); // arg.profile.about
```

**Comment by steph643** [comment]
Cool, thanks.
Doesn't look so pretty, though. I have changed the issue title, in case you want to think about it.

**Comment by zhaoyao91** [comment]
Thanks for your suggestion.
In the soon-coming new version, you can check this object in this way:

```
validate(arg).isObject()
    .validate('id').optional().isString().back()
    .validate('projectId').optional().isString().back()
    .validate('profile').optional().isObject()
        .validate('user').optional().isString().back()
        .validate('picture').optional().isString().back()
        .validate('about').optional().isString().back()
        .back()
    .validate('role').optional().isString();
```

or even briefer:

```
validate(arg).isObject()
    ('id').optional().isString()()
    ('projectId').optional().isString()()
    ('profile').optional().isObject()
        ('user').optional().isString()()
        ('picture').optional().isString()()
        ('about').optional().isString()()
        ()
    ('role').optional().isString();
```

I hope this can help more or less.
I will appreciate if you can share some greater solution or idea.

**Comment by steph643** [comment]
What about this?

``` javascript
validate(arg).isObject({
    id:        optional().isString(),
    projectId: optional().isString(),
    profile:   optional().isObject({
        user:    optional().isString(),
        picture: optional().isString(),
        about:   optional().isString()
    }),
    role:      optional().isString()
});
```

**Comment by zhaoyao91** [comment]
Looks nice. For implementation, I can think out 2 version:
First version

```
validate(arg).isObject({
    id: function(arg){arg.optional().isString()}
    ....
```

If there is lambda support, it will look like:

```
validate(arg).isObject({
    id: arg => arg.optional().isString()
    ....
```

Second version

```
var sf = validate.subField;
validate(arg).isObject({
    id: sf.optional().isString()
    ....
```

How do you think about?

**Comment by zhaoyao91** [comment]
Looks nice. For implementation, I can think out 2 version:
First version

    validate(arg).isObject({
        id: function(){this.optional().isString()}
        ....

If there is lambda support, it will look like:

    validate(arg).isObject({
        id: => this.optional().isString()
        ....

Second version

    var sf = validate.subField;
    validate(arg).isObject({
        id: arg => sf.optional().isString()
        ....

How do you think about?

**Comment by steph643** [comment]
I prefer the first version, but I don't find it so appealing compared to the "check" version.

**Comment by zhaoyao91** [comment]
Thanks for your help. You can treat this package as another flavor of check. I found that client can't know  how checking failed when using Meteor.check directly, so I add some details to the sanitizedError. I also found that although check is good at checking type pattern, it's not convenient for value pattern checking.

**Comment by steph643** [comment]
I don't like the "check" package much. Its syntax is not sexy, error messages are unclear, behavior is unclear (especially when dealing with falsey values), and it is too limited in terms of value checking (gt, lt, list of values, etc.).

I think your package is better, except for one thing: object checking. And this is an important issue, because when you have a function with lots of arguments, you always put them in an object (due to JS lack of argument naming in function calls). And you want your code to start with a very clear and bug-free description of inputs.

Now let's share my dream :-) I would love to have a highly simplified version of the `simple-schema` package, that could be used for both checking and database schema.

**Comment by zhaoyao91** [comment]
I have updated the package and I think there won't be big update in the syntax in a short time. If some better idea get mature, I will consider to fulfill in another project. If you are going to release your work, I am looking forward to :-)
